# Generated by Django 3.2.5 on 2021-11-19 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_artikel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='is_published',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
