# Generated by Django 3.2.5 on 2021-11-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211119_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('publish_artikel', 'Can publish artikel'), ('can_edit', 'Can edit artikel'))},
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='is_published',
        ),
    ]
