# Generated by Django 3.2.5 on 2021-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'jurnal'), ('Blog', 'blog'), ('Berita', 'berita')], default='Blog', max_length=100),
        ),
    ]
