# Generated by Django 3.2.5 on 2021-11-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='content',
            field=models.CharField(default='programing', max_length=100),
            preserve_default=False,
        ),
    ]
