# Generated by Django 3.2.5 on 2021-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(),
        ),
    ]
