# Generated by Django 3.2.5 on 2021-09-16 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_waktu_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='waktu_posting',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
