# Generated by Django 3.2.5 on 2021-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210915_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=255),
        ),
    ]
