# Generated by Django 3.2.5 on 2021-09-16 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210916_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktuPosting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
