# Generated by Django 3.2.5 on 2021-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='nama@web.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
