# Generated by Django 3.2.5 on 2021-09-14 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
